apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
spec:
  selector:
    appName: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: {{ .Values.appPort }}
    targetPort: {{ .Values.appPort }}